functions:
    student_exemple_function: ["text1"]
    student_exemple_two: [1,2]

expected_outputs:
    student_exemple_function: ["Input text is text1"]
    student_exemple_two: [3]

# give each function the ID of the score function used
score_functions:
    student_exemple_function: 0
    student_exemple_two: 0
