# give each function the inputs to be rated with
functions:
    student_exemple_function: ["text1"]
    student_exemple_two: [1,2]

# give each function what outputs are expected
expected_outputs:
    student_exemple_function: ["Input text is text1"]
    student_exemple_two: [3]

# give each function the ID of the score function used
score_functions:
    student_exemple_function: 0
    student_exemple_two: 0

# give each function the maximum amount of time they can be running
timeout_functions:
    student_exemple_function: 2
    student_exemple_two: 2
